name: KLEE Verbosity Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install KLEE from Snap Store
        run: sudo snap install klee --classic

      - name: Compile toy.c to LLVM Bitcode
        run: |
          # Compile toy.c with -O0 to preserve symbolic information.
          clang -I/usr/include/klee -O0 -emit-llvm -c toy.c -o toy.bc

      - name: Run KLEE with Maximum Verbosity
        run: |
          echo "Running KLEE..."
          klee --verbose --write-kqueries toy.bc > klee_verbosity.log 2>&1
          echo "✅ KLEE verbose run completed."

      - name: Upload KLEE Verbosity Log
        uses: actions/upload-artifact@v4
        with:
          name: klee-verbosity-log
          path: klee_verbosity.log
