name: KLEE Verbosity Test (Without Docker)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  klee-verbose:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 hours
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Add KLEE PPA and Install Dependencies
        run: |
          sudo add-apt-repository ppa:klee/klee -y
          sudo apt-get update
          sudo apt-get install -y klee clang llvm
          echo "✅ KLEE, Clang, and LLVM installed."

      - name: Compile toy.c to LLVM Bitcode
        run: |
          # Use -O0 to preserve symbolic information.
          clang -I/usr/include/klee -O0 -emit-llvm -c toy.c -o toy.bc
          echo "✅ toy.c compiled to toy.bc."
      
      - name: List Files in Workspace
        run: |
          echo "Listing workspace files:"
          ls -la

      - name: Run KLEE with Maximum Verbosity
        run: |
          echo "Running KLEE..."
          klee --verbose --write-kqueries toy.bc > klee_verbosity.log 2>&1
          echo "✅ KLEE verbose run completed."
      
      - name: Upload KLEE Verbosity Log
        uses: actions/upload-artifact@v4
        with:
          name: klee-verbosity-log
          path: klee_verbosity.log
