name: KLEE Verbosity Test 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BASE_IMAGE: ubuntu:jammy-20230126
  REPOSITORY: ghcr.io/klee
  COVERAGE: 0
  DISABLE_ASSERTIONS: 0
  ENABLE_DOXYGEN: 0
  ENABLE_OPTIMIZED: 1
  ENABLE_DEBUG: 1
  GTEST_VERSION: 1.11.0
  KLEE_RUNTIME_BUILD: "Debug+Asserts"
  LLVM_VERSION: 13
  MINISAT_VERSION: "master"
  REQUIRES_RTTI: 0
  SOLVERS: STP:Z3
  STP_VERSION: 2.3.3
  TCMALLOC_VERSION: 2.9.1
  UCLIBC_VERSION: klee_uclibc_v1.4
  USE_TCMALLOC: 1
  USE_LIBCXX: 1
  Z3_VERSION: 4.8.15
  SQLITE_VERSION: 3400100

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Checkout KLEE Source
        run: git clone https://github.com/klee/klee.git
      
      - name: Build KLEE
        run: |
          cd klee
          # This builds KLEE and creates a Docker image (named "klee/klee:latest")
          scripts/build/build.sh klee --docker --create-final-image
          cd ..
      
      - name: Compile toy.c to LLVM Bitcode
        run: |
          # Compile toy.c with -O0 to preserve symbolic information.
          clang -I/usr/include/klee -O0 -emit-llvm -c toy.c -o toy.bc
      
      - name: Run KLEE with Maximum Verbosity
        run: |
          echo "Running KLEE..."
          docker run --rm -v ${{ github.workspace }}:/workspace klee/klee:latest \
            klee --verbose --write-kqueries /workspace/toy.bc > klee_verbosity.log 2>&1
          echo "✅ KLEE verbose run completed."
      
      - name: Upload KLEE Verbosity Log
        uses: actions/upload-artifact@v4
        with:
          name: klee-verbosity-log
          path: klee_verbosity.log
