name: Build KLEE

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout KLEE Source
        uses: actions/checkout@v3

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg build-essential cmake

          # Add LLVM APT repository for LLVM 13 on Ubuntu 22.04 (jammy)
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          echo "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-13 main" | sudo tee /etc/apt/sources.list.d/llvm.list
          sudo apt-get update
          # Install LLVM 13 and its tools along with Z3 solver dependency
          sudo apt-get install -y clang-13 llvm-13 llvm-13-dev llvm-13-tools libz3-dev

      - name: Configure KLEE Build
        run: |
          mkdir build
          cd build
          # Configure KLEE with Z3 support and ensure LLVM 13 is used
          cmake -DENABLE_SOLVER_Z3=ON -DLLVM_CONFIG=llvm-config-13 ..

      - name: Build KLEE
        run: |
          cd build
          make -j$(nproc)

      - name: Run Tests (Optional)
        run: |
          cd build
          make check
